import { ScanbotDocument, ScanbotSDK } from 'capacitor-plugin-scanbot-sdk';

async function createDocument() {
  /** Create a document with an uuid */
  const document = ScanbotDocument.createDocumentFromImages({});
}

async function createDocumentWithPages(imageFileUris: string[]) {
  /**
   * Create a document with an uuid
   * Add images from `imageFileUris` as document pages
   */
  const document = ScanbotDocument.createDocumentFromImages({
    images: imageFileUris,
  });
}

async function createDocumentFromPDF(pdfUri: string) {
  /**
   * Create a document with an uuid
   * Extract images from the PDF file and add them as document pages
   */
  const document = ScanbotDocument.createDocumentFromPdf({ pdfFileUri: pdfUri });
}

async function loadDocument(documentUuid: string) {
  /** Load a document from storage by ID */
  const document = await ScanbotDocument.loadDocument(documentUuid);
}

async function storedDocumentUUIDs() {
  /** Retrieve all the document ids from the storage */
  const documentUuids = await ScanbotDocument.getStoredDocumentUuids();
}

async function reorderDocumentPages(documentUuid: string) {
  /** Load a document from storage by ID */
  const document = await ScanbotDocument.loadDocument(documentUuid);
  /** Swap the first and last page of the document */
  const documentWithReorderedPages = await ScanbotDocument.movePage({
    documentUuid: document.uuid,
    fromIndex: 0,
    toIndex: document.pages.length - 1,
  });
}

async function removeAllPagesFromDocument(documentUuid: string) {
  /** Remove all the pages from a document */
  const documentWithRemovedPages = await ScanbotDocument.removeAllPages(documentUuid);
}

async function deleteDocument(documentUuid: string) {
  /** Delete a document from storage along with the document's PDF and TIFF files */
  await ScanbotDocument.deleteDocument(documentUuid);
}

async function deleteAllDocuments() {
  /** Delete all documents from storage along with the document's PDF and TIFF files */
  await ScanbotDocument.deleteAllDocuments();
}

async function cleanup() {
  /** Removes all the files generated by ScanbotSDK including the documents */
  await ScanbotSDK.cleanupStorage();
}
